- name: Deploy my-app to Kubernetes
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Apply deployment file
    command: kubectl apply -f {{ deployment_file }} 
    args:
      chdir: k8
  - name: Apply service file
    command: kubectl apply -f {{ service_file }} 
    args:
      chdir: k8
  - name: Wait for deployment to complete
    command: kubectl rollout status deployment/{{ app_name }} 
    args:
      chdir: k8
  - name: Apply Ingress configuration
    command: kubectl apply -f {{ ingress_file }} 
    args:
      chdir: k8
